version: '2.1'
name: team-service
services:
  databaseteam:
    image: postgres:latest
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB:       "saop_prod_team"
      POSTGRES_HOST_AUTH_METHOD: trust 
      PGPORT: 5433
    networks:
      backend:
        aliases:
          - "database team"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  configserverteam:
    image: saop/configserverteam:0.0.1-SNAPSHOT
    ports:
       - "8072:8072"
    networks:
      backend:
        aliases:
          - "configserverteam"
  teamservice:
    image: saop/teamservice:0.0.2-SNAPSHOT
    environment:
      PROFILE: "prod-team"
      CONFIGSERVER_URI: "http://configserverteam:8072"
      CONFIGSERVER_PORT:   "8072"
      DATABASESERVER_PORT: "5433"
    depends_on:
      databaseteam:
        condition: service_healthy
      configserverteam:
        condition: service_started
    ports:
      - "8081:8081"
    networks:
      - backend

networks:
  backend:
    driver: bridge